<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TheatreSeeder extends Seeder
{
    public function run(): void
    {
        $theatres = [
            [
                'branch_id' => 1,
                'theatre_number' => 1,
                'theatre_name' => null,
                'Type_name' => 'Laser',
                'special_format' => null,
                'lamp_type' => 'Laser',
                'seat_count' => 89,
                'screen_width' => 8.32,
                'screen_height' => 3.40,
                'throw_distance' => 13.90,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '396310',
                'projector_make' => 'Christie',
                'projector_model' => 'CP2208LP',
                'projector_serial' => '412690011',
                'three_d_type' => null,
                'initial_installation' => '2016-11-29',
                'new_screen_installed_at' => '2022-10-06',
                'version' => null,
                'client_ip' => '10.131.10.10',
                'projector_ip' => '10.131.10.11',
            ],

            [
                'branch_id' => 1,
                'theatre_number' => 2,
                'theatre_name' => null,
                'Type_name' => 'Laser',
                'special_format' => null,
                'lamp_type' => 'Laser',
                'seat_count' => 96,
                'screen_width' => 7.51,
                'screen_height' => 3.21,
                'throw_distance' => 14.80,
                'server_make' => 'Doremi',
                'server_model' => 'IMB-4K',
                'server_serial' => '287564',
                'projector_make' => 'NEC',
                'projector_model' => 'NC1201L',
                'projector_serial' => '98A0015ET',
                'three_d_type' => null,
                'initial_installation' => '2020-01-01',
                'new_screen_installed_at' => '2020-01-01',
                'version' => null,
                'client_ip' => '10.131.10.20',
                'projector_ip' => '10.131.10.21',
            ],

            [
                'branch_id' => 1,
                'theatre_number' => 3,
                'theatre_name' => null,
                'Type_name' => 'Laser',
                'special_format' => 'Kids',
                'lamp_type' => 'Laser',
                'seat_count' => 282,
                'screen_width' => 11.53,
                'screen_height' => 4.91,
                'throw_distance' => 18.00,
                'server_make' => 'Doremi',
                'server_model' => 'IMB-4K',
                'server_serial' => '296426',
                'projector_make' => 'NEC',
                'projector_model' => 'NC1201L',
                'projector_serial' => '89A0006EJ',
                'three_d_type' => null,
                'initial_installation' => '2022-10-06',
                'new_screen_installed_at' => '2022-10-06',
                'version' => null,
                'client_ip' => '10.131.10.30',
                'projector_ip' => '10.131.10.31',
            ],

            [
                'branch_id' => 1,
                'theatre_number' => 4,
                'theatre_name' => null,
                'Type_name' => 'Laser',
                'special_format' => null,
                'lamp_type' => 'Laser',
                'seat_count' => 166,
                'screen_width' => 8.50,
                'screen_height' => 3.52,
                'throw_distance' => 20.40,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '396315',
                'projector_make' => 'NEC',
                'projector_model' => 'NC1201L',
                'projector_serial' => '79A0011EG',
                'three_d_type' => null,
                'initial_installation' => '2022-10-06',
                'new_screen_installed_at' => '2022-10-06',
                'version' => null,
                'client_ip' => '10.131.10.40',
                'projector_ip' => '10.131.10.41',
            ],

            // 5
            [
                'branch_id' => 1,
                'theatre_number' => 5,
                'theatre_name' => null,
                'Type_name' => 'Laser',
                'special_format' => 'ATMOS',
                'lamp_type' => 'Laser',
                'seat_count' => 313,
                'screen_width' => 12.01,
                'screen_height' => 5.01,
                'throw_distance' => 19.00,
                'server_make' => 'Doremi',
                'server_model' => 'IMB-4K',
                'server_serial' => '297794',
                'projector_make' => 'NEC',
                'projector_model' => 'NC1201L',
                'projector_serial' => '89A0007EJ',
                'three_d_type' => null,
                'initial_installation' => '2024-04-06',
                'new_screen_installed_at' => '2024-04-06',
                'version' => null,
                'client_ip' => '10.131.10.50',
                'projector_ip' => '10.131.10.51',
            ],

            // 6
            [
                'branch_id' => 1,
                'theatre_number' => 6,
                'theatre_name' => null,
                'Type_name' => 'Laser',
                'special_format' => null,
                'lamp_type' => 'Laser',
                'seat_count' => 236,
                'screen_width' => 10.50,
                'screen_height' => 4.48,
                'throw_distance' => 19.00,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '369266',
                'projector_make' => 'NEC',
                'projector_model' => 'NC1202L',
                'projector_serial' => '19A0003CD',
                'three_d_type' => null,
                'initial_installation' => '2021-12-10',
                'new_screen_installed_at' => '2021-12-10',
                'version' => null,
                'client_ip' => '10.131.10.60',
                'projector_ip' => '10.131.10.61',
            ],

            // 7
            [
                'branch_id' => 1,
                'theatre_number' => 7,
                'theatre_name' => null,
                'Type_name' => 'Laser',
                'special_format' => null,
                'lamp_type' => 'Laser',
                'seat_count' => 229,
                'screen_width' => 11.99,
                'screen_height' => 5.10,
                'throw_distance' => 19.00,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '369307',
                'projector_make' => 'NEC',
                'projector_model' => 'NC1202L',
                'projector_serial' => '19A0012CD',
                'three_d_type' => null,
                'initial_installation' => '2021-12-10',
                'new_screen_installed_at' => '2021-12-10',
                'version' => null,
                'client_ip' => '10.131.10.70',
                'projector_ip' => '10.131.10.71',
            ],

            // 8
            [
                'branch_id' => 1,
                'theatre_number' => 8,
                'theatre_name' => null,
                'Type_name' => 'Laser',
                'special_format' => null,
                'lamp_type' => 'Laser',
                'seat_count' => 193,
                'screen_width' => 9.89,
                'screen_height' => 4.12,
                'throw_distance' => 19.00,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '369295',
                'projector_make' => 'NEC',
                'projector_model' => 'NC1202L',
                'projector_serial' => '17A0001CD',
                'three_d_type' => null,
                'initial_installation' => '2021-12-10',
                'new_screen_installed_at' => '2021-12-10',
                'version' => null,
                'client_ip' => '10.131.10.80',
                'projector_ip' => '10.131.10.81',
            ],

            // 9
            [
                'branch_id' => 1,
                'theatre_number' => 9,
                'theatre_name' => null,
                'Type_name' => 'Laser',
                'special_format' => null,
                'lamp_type' => 'Laser',
                'seat_count' => 176,
                'screen_width' => 8.51,
                'screen_height' => 4.60,
                'throw_distance' => 19.20,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '369298',
                'projector_make' => 'NEC',
                'projector_model' => 'NC1202L',
                'projector_serial' => '17A0007CD',
                'three_d_type' => null,
                'initial_installation' => '2021-12-10',
                'new_screen_installed_at' => '2021-12-10',
                'version' => null,
                'client_ip' => '10.131.10.90',
                'projector_ip' => '10.131.10.91',
            ],

            // 10
            [
                'branch_id' => 1,
                'theatre_number' => 10,
                'theatre_name' => null,
                'Type_name' => 'Laser',
                'special_format' => null,
                'lamp_type' => 'Laser',
                'seat_count' => 180,
                'screen_width' => 8.52,
                'screen_height' => 4.60,
                'throw_distance' => 19.30,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '369306',
                'projector_make' => 'NEC',
                'projector_model' => 'NC1202L',
                'projector_serial' => '19A0013CD',
                'three_d_type' => null,
                'initial_installation' => '2022-10-06',
                'new_screen_installed_at' => '2022-10-06',
                'version' => null,
                'client_ip' => '10.131.10.100',
                'projector_ip' => '10.131.10.101',
            ],

            // 11
            [
                'branch_id' => 1,
                'theatre_number' => 11,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB',
                'special_format' => null,
                'lamp_type' => null,
                'seat_count' => 164,
                'screen_width' => 15.00,
                'screen_height' => 5.50,
                'throw_distance' => 15.70,
                'server_make' => 'Christie',
                'server_model' => 'CP2315-RGB',
                'server_serial' => '498126012',
                'projector_make' => 'Christie',
                'projector_model' => 'CP2315-RGB',
                'projector_serial' => '498126012',
                'three_d_type' => null,
                'initial_installation' => '2023-10-09',
                'new_screen_installed_at' => '2023-10-09',
                'version' => null,
                'client_ip' => '10.131.10.110',
                'projector_ip' => '10.131.10.111',
            ],

            // 12
            [
                'branch_id' => 1,
                'theatre_number' => 12,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB',
                'special_format' => null,
                'lamp_type' => null,
                'seat_count' => 247,
                'screen_width' => 15.50,
                'screen_height' => 6.57,
                'throw_distance' => 15.70,
                'server_make' => 'Christie',
                'server_model' => 'CP2320-RGB',
                'server_serial' => '495993014',
                'projector_make' => 'Christie',
                'projector_model' => 'CP2320-RGB',
                'projector_serial' => '495993014',
                'three_d_type' => null,
                'initial_installation' => '2023-10-09',
                'new_screen_installed_at' => '2023-10-09',
                'version' => null,
                'client_ip' => '10.131.10.120',
                'projector_ip' => '10.131.10.121',
            ],

            // 13
            [
                'branch_id' => 1,
                'theatre_number' => 13,
                'theatre_name' => null,
                'Type_name' => 'Laser RB',
                'special_format' => null,
                'lamp_type' => null,
                'seat_count' => 729,
                'screen_width' => 22.30,
                'screen_height' => 9.23,
                'throw_distance' => 34.50,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '7YA0006CE',
                'projector_make' => 'NEC',
                'projector_model' => 'NC3541L',
                'projector_serial' => '7YA0006CE',
                'three_d_type' => null,
                'initial_installation' => '2024-12-24',
                'new_screen_installed_at' => '2024-12-24',
                'version' => null,
                'client_ip' => '10.131.10.130',
                'projector_ip' => '10.131.10.131',
            ],

            // 14
            [
                'branch_id' => 1,
                'theatre_number' => 14,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB',
                'special_format' => null,
                'lamp_type' => null,
                'seat_count' => 488,
                'screen_width' => 17.38,
                'screen_height' => 7.43,
                'throw_distance' => 23.50,
                'server_make' => 'Barco',
                'server_model' => 'ICMPX',
                'server_serial' => '9731281313',
                'projector_make' => 'Christie',
                'projector_model' => 'CP230-RGB',
                'projector_serial' => '472042019',
                'three_d_type' => null,
                'initial_installation' => '2023-10-09',
                'new_screen_installed_at' => '2023-10-09',
                'version' => null,
                'client_ip' => '10.131.10.140',
                'projector_ip' => '10.131.10.141',
            ],

            // 15 – IMAX
            [
                'branch_id' => 1,
                'theatre_number' => 15,
                'theatre_name' => null,
                'Type_name' => 'IMAX',
                'special_format' => 'IMAX',
                'lamp_type' => 'Laser RGB',
                'seat_count' => 488,
                'screen_width' => 24.00,
                'screen_height' => 16.70,
                'throw_distance' => null,
                'server_make' => 'IMAX',
                'server_model' => 'COLA',
                'server_serial' => '1074034',
                'projector_make' => 'Barco',
                'projector_model' => 'ICMPX',
                'projector_serial' => '9731281313',
                'three_d_type' => 'IMAX 3D',
                'initial_installation' => '2023-10-09',
                'new_screen_installed_at' => '2023-10-09',
                'version' => null,
                'client_ip' => '', 
            ],
        ];

        foreach ($theatres as $theatre) {
         DB::table('theatres')->updateOrInsert(
        [
            'branch_id' => $theatre['branch_id'],
            'theatre_number' => $theatre['theatre_number'],
        ],
            $theatre
          );
        }

    }
}
