<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TheatreParagonSeeder extends Seeder
{
    public function run(): void
    {
        $theatres = [

            // 1
            [
                'branch_id' => 2,
                'theatre_number' => 1,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB',
                'special_format' => null,
                'lamp_type' => 'Laser RGB',
                'seat_count' => 72,
                'screen_width' => 14.10,
                'screen_height' => 9.50,
                'throw_distance' => 22.36,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '398693',
                'projector_make' => 'Christie',
                'projector_model' => 'CP2315-RGB',
                'projector_serial' => '500389018',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => null,
                'version' => null,
                'client_ip' => '10.131.1.x',
            ],

            // 2
            [
                'branch_id' => 2,
                'theatre_number' => 2,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB',
                'special_format' => null,
                'lamp_type' => 'Laser RGB',
                'seat_count' => 1159,
                'screen_width' => 23.50,
                'screen_height' => 9.60,
                'throw_distance' => 34.44,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '397000009',
                'projector_make' => 'Christie',
                'projector_model' => 'CP42LHE',
                'projector_serial' => '397007009',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => '2019-07-01',
                'version' => null,
                'client_ip' => '10.131.4.x',
            ],

            // 3
            [
                'branch_id' => 2,
                'theatre_number' => 3,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB',
                'special_format' => null,
                'lamp_type' => 'Laser RGB',
                'seat_count' => 1159,
                'screen_width' => 23.50,
                'screen_height' => 9.60,
                'throw_distance' => 34.44,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '378346',
                'projector_make' => 'Christie',
                'projector_model' => 'CP4330-RGB',
                'projector_serial' => '486161001',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => '2019-07-01',
                'version' => null,
                'client_ip' => '10.131.4.x',
            ],

            // 4 
            [
                'branch_id' => 2,
                'theatre_number' => 4,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB+',
                'special_format' => '4DX',
                'lamp_type' => 'Laser RGB+',
                'seat_count' => 140,
                'screen_width' => 14.85,
                'screen_height' => 6.70,
                'throw_distance' => 20.86,
                'server_make' => 'GDC',
                'server_model' => 'SX4000',
                'server_serial' => 'A447796',
                'projector_make' => 'Barco',
                'projector_model' => 'DP2K-20C+',
                'projector_serial' => '2530569790',
                'three_d_type' => 'RealD XL',
                'initial_installation' => null,
                'new_screen_installed_at' => null,
                'version' => null,
                'client_ip' => '10.131.5.x',
            ],

            // 5
            [
                'branch_id' => 2,
                'theatre_number' => 5,
                'theatre_name' => null,
                'Type_name' => 'LED',
                'special_format' => null,
                'lamp_type' => 'LED',
                'seat_count' => 278,
                'screen_width' => 10.30,
                'screen_height' => 5.50,
                'throw_distance' => 21.38,
                'server_make' => 'GDC',
                'server_model' => 'SX4000',
                'server_serial' => 'G047727',
                'projector_make' => 'Samsung',
                'projector_model' => 'Samsung LED',
                'projector_serial' => null,
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => null,
                'version' => null,
                'client_ip' => '10.131.6.x',
            ],

            // 6
            [
                'branch_id' => 2,
                'theatre_number' => 6,
                'theatre_name' => 'ScreenX',
                'Type_name' => 'Laser RGB+',
                'special_format' => 'ScreenX',
                'lamp_type' => 'Laser RGB+',
                'seat_count' => 299,
                'screen_width' => 15.54,
                'screen_height' => 8.10,
                'throw_distance' => 20.82,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '363234',
                'projector_make' => 'Barco',
                'projector_model' => 'DP2K-20C+',
                'projector_serial' => '2530744958',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => '2022-08-07',
                'version' => null,
                'client_ip' => '10.131.7.x',
            ],

            // 7
            [
                'branch_id' => 2,
                'theatre_number' => 7,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB+',
                'special_format' => null,
                'lamp_type' => 'Laser RGB+',
                'seat_count' => 336,
                'screen_width' => 14.90,
                'screen_height' => 7.20,
                'throw_distance' => 22.80,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '380267',
                'projector_make' => 'Christie',
                'projector_model' => 'CP2320-RGB',
                'projector_serial' => '472042003',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => '2024-06-26',
                'version' => null,
                'client_ip' => '10.131.8.x',
            ],

            // 8
            [
                'branch_id' => 2,
                'theatre_number' => 8,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB+',
                'special_format' => null,
                'lamp_type' => 'Laser RGB+',
                'seat_count' => 299,
                'screen_width' => 14.25,
                'screen_height' => 5.90,
                'throw_distance' => 20.80,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '373490',
                'projector_make' => 'Barco',
                'projector_model' => 'DP2K-20C+',
                'projector_serial' => '2530524691',
                'three_d_type' => 'HCBL 3D',
                'initial_installation' => null,
                'new_screen_installed_at' => '2022-08-07',
                'version' => null,
                'client_ip' => '10.131.9.x',
            ],

            // 9
            [
                'branch_id' => 2,
                'theatre_number' => 9,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB',
                'special_format' => null,
                'lamp_type' => 'Laser RGB',
                'seat_count' => 336,
                'screen_width' => 14.90,
                'screen_height' => 7.20,
                'throw_distance' => 22.80,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '381203',
                'projector_make' => 'Christie',
                'projector_model' => 'CP2320-RGB',
                'projector_serial' => '472042005',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => '2024-07-05',
                'version' => null,
                'client_ip' => '10.131.10.x',
            ],

            // 10
            [
                'branch_id' => 2,
                'theatre_number' => 10,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB+',
                'special_format' => null,
                'lamp_type' => 'Laser RGB+',
                'seat_count' => 299,
                'screen_width' => 14.25,
                'screen_height' => 5.90,
                'throw_distance' => 20.88,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '398656',
                'projector_make' => 'Barco',
                'projector_model' => 'DP2K-20C+',
                'projector_serial' => '2531058590',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => null,
                'version' => null,
                'client_ip' => '10.131.11.x',
            ],

            // 11
            [
                'branch_id' => 2,
                'theatre_number' => 11,
                'theatre_name' => 'Kids',
                'Type_name' => 'Laser RGB',
                'special_format' => 'Kids',
                'lamp_type' => 'Laser RGB',
                'seat_count' => 245,
                'screen_width' => 10.50,
                'screen_height' => 4.48,
                'throw_distance' => 20.00,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '397933',
                'projector_make' => 'Christie',
                'projector_model' => 'CP2315-RGB',
                'projector_serial' => '471660104',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => null,
                'version' => null,
                'client_ip' => '10.131.12.x',
            ],

            // 12
            [
                'branch_id' => 2,
                'theatre_number' => 12,
                'theatre_name' => null,
                'Type_name' => 'Laser RB',
                'special_format' => null,
                'lamp_type' => 'Laser RB',
                'seat_count' => 245,
                'screen_width' => 10.50,
                'screen_height' => 4.48,
                'throw_distance' => 20.00,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '397425',
                'projector_make' => 'NEC',
                'projector_model' => 'NC1202L',
                'projector_serial' => '17A0007CD',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => null,
                'version' => null,
                'client_ip' => '10.131.13.x',
            ],

            // 13
            [
                'branch_id' => 2,
                'theatre_number' => 13,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB',
                'special_format' => null,
                'lamp_type' => 'Laser RGB',
                'seat_count' => 245,
                'screen_width' => 13.20,
                'screen_height' => 5.20,
                'throw_distance' => 20.23,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '298944',
                'projector_make' => 'Christie',
                'projector_model' => 'CP2315-RGB',
                'projector_serial' => '498126010',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => null,
                'version' => null,
                'client_ip' => '10.131.14.x',
            ],

            // 14
            [
                'branch_id' => 2,
                'theatre_number' => 14,
                'theatre_name' => null,
                'Type_name' => 'Laser RGB',
                'special_format' => null,
                'lamp_type' => 'Laser RGB',
                'seat_count' => 34,
                'screen_width' => 9.75,
                'screen_height' => 5.50,
                'throw_distance' => 18.77,
                'server_make' => 'Dolby',
                'server_model' => 'IMS3000',
                'server_serial' => '380229',
                'projector_make' => 'Christie',
                'projector_model' => 'CP2308-RGB',
                'projector_serial' => '554123010',
                'three_d_type' => null,
                'initial_installation' => null,
                'new_screen_installed_at' => null,
                'version' => null,
                'client_ip' => '10.131.15.x',
            ],

            // IMAX (โรง 15)
            [
                'branch_id' => 2,
                'theatre_number' => 15,
                'theatre_name' => 'IMAX',
                'Type_name' => 'Laser RGB',
                'special_format' => 'IMAX',
                'lamp_type' => 'Laser RGB',
                'seat_count' => 491,
                'screen_width' => 28.00,
                'screen_height' => 21.00,
                'throw_distance' => null,
                'server_make' => 'Barco',
                'server_model' => 'ICMPX',
                'server_serial' => '9730692054',
                'projector_make' => 'Barco',
                'projector_model' => 'COLA',
                'projector_serial' => '1067619',
                'three_d_type' => 'IMAX',
                'initial_installation' => null,
                'new_screen_installed_at' => null,
                'version' => null,
                'client_ip' => null,
            ],
        ];

        foreach ($theatres as $theatre) {
              DB::table('theatres')->updateOrInsert(
            [
             'branch_id' => $theatre['branch_id'],
             'theatre_number' => $theatre['theatre_number'],
            ],
            $theatre
            );
        }

    }
}

// php artisan db:seed --class=TheatreParagonSeeder